on: 
  pull_request:
  push:
    branches:
      - main
jobs:
  cio:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v4
    - run: cargo run
