name: Continous Integration

on: 
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  cio:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v4

    #- name: Install Rust Stable
    #  uses: actions-rs/toolchain@v1
    #  with:
    #    toolchain: stable
    #    components: clippy
    #    target: wasm32-unknown-unknown

    - name: Build
      run: cargo run
